ALTER TABLE "Client" ALTER COLUMN "id" SET DATA TYPE VARCHAR(24);

ALTER TABLE "LegalTerms" ALTER COLUMN "id" SET DATA TYPE VARCHAR(24);

ALTER TABLE "Shirt" ALTER COLUMN "id" SET DATA TYPE VARCHAR(24);

ALTER TABLE "ShirtOrder" ALTER COLUMN "id" SET DATA TYPE VARCHAR(24);
